from schematics.models import Model
from schematics.types import URLType, StringType, ListType, FloatType, DateTimeType, IntType, BooleanType, ModelType

class VariantItem(Model):
    id = IntType()
    title = StringType()
    option1 = StringType()
    option2 = StringType()
    option3 = StringType()
    sku = StringType()
    requires_shipping = BooleanType()
    taxable = BooleanType()
    featured_image = StringType()
    available = BooleanType()
    name = StringType()
    public_title = StringType()
    options = ListType(StringType)
    price = FloatType()
    weight = IntType()
    compare_at_price = FloatType()
    inventory_management = StringType()
    barcode = StringType()

class KingsItem(Model):
    id = IntType()
    title = StringType(required=True)
    handle = StringType()
    description = StringType()
    published_at = DateTimeType()
    created_at = DateTimeType()
    vendor = StringType()
    type = StringType()
    tags = ListType(StringType)
    available = BooleanType()
    price_varies = BooleanType()
    compare_at_price = FloatType()
    compare_at_price_varies = BooleanType()
    image_urls = ListType(URLType)
    image_uris = ListType(StringType)
    reference_first_image = StringType()
    sku = StringType(regex="^[0-9A-Z]{6}$", required=True)
    sku_alt = ListType(StringType)
    endpoint = URLType()
    url = URLType()
    variants = ListType(ModelType(VariantItem))
    price = FloatType(required=True)
    price_min = FloatType()
    price_max = FloatType()
    compare_at_price_min = FloatType()
    compare_at_price_max = FloatType()
    timestamp = StringType()
    spider = StringType()
    spider_version = StringType()
